---
title: "Note_Apr22"
author: "Qi"
date: "2025-04-22"
output: pdf_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
rm(list = ls())
# install.packages("here")
# library(here)
here::here()
getwd()
read.table()
x <- 1
# install.packages("ggplot2")
```
```{r}
library(ggplot2)
dat <- mtcars
ggplot() +
geom_point(aes(y = dat$mpg, x = dat$wt), color = "#FF8788", shape = 19, size = 5) +
  labs(x = "Weight", y = "MPG", title = "Scatter Plot of Weight and MPG") +
  theme_bw(base_size = 10) +
  theme(plot.title = element_text(hjust = 0.5))
```
```{r}
library(mvtnorm)
mean_vec <- rep(0,2)
Sig <- matrix(c(1,0.5,0.5,1),2,2)
simulations <- rmvnorm(10000, mean = mean_vec, sigma = Sig)
ggplot() +
  geom_point(aes(x = simulations[,1], y = simulations[,2]), alpha = 0.1)
```
```{r}
library(tidyr)
library(lubridate) # Ensure proper date handling
set.seed(123)
time_series_data <- data.frame(
date = seq(as.Date("2023-01-01"), by = "month", length.out = 12),
series_A = cumsum(rnorm(12, mean = 5, sd = 2)),
series_B = cumsum(rnorm(12, mean = 3, sd = 1.5)),
series_C = cumsum(rnorm(12, mean = 4, sd = 1.8))
)
long_data <- time_series_data %>%
pivot_longer(cols = -date, names_to = "series", values_to = "value")
```


```{r}
ggplot(long_data, aes(x = date, y = value, color = series, linetype = series)) +
geom_line(linewidth = 1.2) +
geom_point(size = 2) +
scale_x_date(date_labels = "%b %Y") +
labs(
title = "Multiple Time Series Plot",
x = "Date",
y = "Value",
color = "Series"
) +
theme_minimal(base_size = 14) +
theme(legend.position = "top")


time_series_data
plot(x = 1:nrow(time_series_data), y = time_series_data[,2], xlab = "Time", ylab = "Value",
     main = "Time Series Plot", pch = 19, lwd = 5, lty = 2, type = 'p', col = "red")
lines(x = 1:nrow(time_series_data), y = time_series_data[,3], pch = 19, lwd = 5, lty = 2, type = 'p', col = "blue")

```

```{r warning=FALSE}
library(ggplot2)

# Generate random samples from a normal distribution
set.seed(123)  # For reproducibility
data <- data.frame(value = rnorm(1000, mean = 50, sd = 10))

# Create histogram with a density line
ggplot(data, aes(x = value)) +
  geom_histogram(aes(y = ..density..), binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  geom_density(color = "red", size = 1.2, linetype = "dotted") +  # Add a smooth density line
  labs(
    title = "Histogram with Density Curve",
    x = "Value",
    y = "Density"
  ) +
  theme(plot.title = element_text(hjust = 0.5))

value = rnorm(1000, mean = 50, sd = 10)
mean(value)
sd(value)
median(value)
quantile(value,0.5)
summary(value)
library(ggcorrplot)
?ggcorrplot
```


```{r}
expand.grid(1:10,1:10)
```

This is an example of data visualization based on iris dataset in R.
```{r}
library(ggplot2)
data(iris)
head(iris)

# Scatter plot of Sepal.Length vs Sepal.Width
p1 <- ggplot(iris, aes(x = Petal.Length, y = Petal.Width)) +
  geom_point(aes(color = Species)) +
  labs(title = "Scatter Plot of Petal Length vs Petal Width") +
  theme_minimal()
cor(
  iris$Sepal.Length[which(iris$Species == "virginica")],
  iris$Sepal.Width[which(iris$Species == "virginica")]
  )
```
```{r}
# Boxplot of Petal.Length by Species
p2 <- ggplot(iris, aes(x = Species, y = Petal.Length, fill = Species)) +
  geom_boxplot() +
  labs(title = "Boxplot of Petal Length by Species") +
  theme_minimal()

cowplot::plot_grid(p1,p2)
```

```{r}
set.seed(0)
X <- matrix(runif(5000), ncol = 5)
Y <- 0.9 + X[,1]*4 + X[,2]*0.6 + X[,3]*1.5 - X[,4]*2.5 - X[,5]*5.8 + rnorm(nrow(X),0,1)
colnames(X) <- c("Sunshine","Rain","Carbon","Bugs","Disease")
apple_data <- data.frame(cbind(Y,X))
linear_model <- lm(Y ~ . , data = apple_data)
results <- summary(linear_model)
Y_hat <- predict(linear_model)

res <- linear_model$residuals
boxplot(res)
hist(res)
# plot(Y, Y_hat)
plot(rnorm(100))
```





